version: 2
references:
  docker_image: &docker_image
    docker:
      - image: gableroux/unity3d:2019.3.5f1
  setup_unity_license_env_var: &setup_unity_license_env_var
    command: |
      mkdir -p /root/.cache/unity3d
      mkdir -p /root/.local/share/unity3d/Unity/
      openssl version
      openssl aes-256-cbc -md md5 -d -in ./Unity_v2019.x.ulf-garbled -out /Unity_v2019.x.ulf -k $KEY
      export UNITY_LICENSE_CONTENT=`cat /Unity_v2019.x.ulf`
      echo "$UNITY_LICENSE_CONTENT" | tr -d '\r' > "/root/.local/share/unity3d/Unity/Unity_lic.ulf"
  remove_license_file: &remove_license_file
    command: |
      rm /Unity_v2019.x.ulf
      rm /root/.local/share/unity3d/Unity/Unity_lic.ulf
jobs:
  build_packaging:
    <<: *docker_image
    steps:
      - checkout
      - run:
          <<: *setup_unity_license_env_var
      - run:
          command: |
            chmod -R 755 ./Builds/BuildLX.sh
            ./Builds/BuildLX.sh
      - run:
          <<: *remove_license_file
      - store_artifacts:
          path: './Builds/*.unitypackage'
workflows:
  version: 2
  build:
    jobs:
      - build_packaging
