version: 2
jobs:
  build-packaging:
    docker:
      - image: gableroux/unity3d:2019.3.5f1
    steps:
      - checkout
      - run: openssl aes-256-cbc -md md5 -d -in ./.circleci/Unity_v2019.x.ulf-garbled -out /Unity_v2019.x.ulf -k $EXPAND_KEY
      - run: /opt/Unity/Editor/Unity -batchmode -nographics -quit -silent-crashes -noUpm -logFile /dev/stdout -projectPath ./ -manualLicenseFile /Unity_v2019.x.ulf || echo
      - run: /opt/Unity/Editor/Unity -batchmode -nographics -quit -silent-crashes -logFile /dev/stdout -projectPath ./ -executeMethod Com.FurtherSystems.OpenRelay.Builds.OpenRelayCDKBuildMenu.BuildALL
      - run: rm /Unity_v2019.x.ulf
      - store_artifacts:
          path: ./Builds/${PACKAGE_PREFIX}-${CDK_VERSION}.unitypackage
          destination: ${PACKAGE_PREFIX}-${CDK_VERSION}.unitypackage
workflows:
  version: 2
  build:
    jobs:
      - build-packaging
